INSERT INTO CATEGORIA(CODIGO, DESCRICAO) VALUES(1, 'COMPORTAMENTAL');
INSERT INTO CATEGORIA(CODIGO, DESCRICAO) VALUES(2, 'PROGRAMAÇÃO');
INSERT INTO CATEGORIA(CODIGO, DESCRICAO) VALUES(3, 'QUALIDADE');
INSERT INTO CATEGORIA(CODIGO, DESCRICAO) VALUES(4, 'PROCESSOS');

INSERT INTO CURSO(ID, DESCRICAO, DATA_INICIO, DATA_TERMINO, QNT_ALUNOS, CATEGORIA_CODIGO) VALUES(NULL, 'Curso Comportamental', '2020-07-01', '2020-07-31', 30, 1);
INSERT INTO CURSO(ID, DESCRICAO, DATA_INICIO, DATA_TERMINO, QNT_ALUNOS, CATEGORIA_CODIGO) VALUES(NULL, 'Programação Orientada a Objetos', '2020-08-01', '2020-08-30', 30, 2);
INSERT INTO CURSO(ID, DESCRICAO, DATA_INICIO, DATA_TERMINO, QNT_ALUNOS, CATEGORIA_CODIGO) VALUES(NULL, 'Engenharia de Software', '2020-10-01', '2020-10-31', 30, 3);
INSERT INTO CURSO(ID, DESCRICAO, DATA_INICIO, DATA_TERMINO, QNT_ALUNOS, CATEGORIA_CODIGO) VALUES(NULL, 'Processos de Negócios', '2020-11-01', '2020-11-30', 30, 4);


