INSERT INTO CATEGORIA(CODIGO, DESCRICAO) VALUES(1, 'COMPORTAMENTAL');
INSERT INTO CATEGORIA(CODIGO, DESCRICAO) VALUES(2, 'PROGRAMAÇÃO');
INSERT INTO CATEGORIA(CODIGO, DESCRICAO) VALUES(3, 'QUALIDADE');
INSERT INTO CATEGORIA(CODIGO, DESCRICAO) VALUES(4, 'PROCESSOS');

INSERT INTO CURSO(ID, DESCRICAO, DATA_INICIO, DATA_TERMINO, QNT_ALUNOS, CATEGORIA_CODIGO)
    VALUES(NULL, 'Programação Orientada a Objetos', '2020-08-01', '2020-09-01', 30, 2);

