DROP TABLE IF EXISTS CURSO;

CREATE TABLE CURSO (
    ID INT AUTO_INCREMENT,
    DESCRICAO VARCHAR(50) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_TERMINO DATE NOT NULL,
    QNT_ALUNOS INT,
    CATEGORIA INT,
    PRIMARY KEY(ID),
    UNIQUE(DESCRICAO)
);